# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0002_thread_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
